// Pyodide bridge: bootstrap, build_curve calls, downloads, YAML import/export.
import {
  curves,
  current,
  freshRecipe,
  loadFromStorage,
  outputCfg,
  pyReady,
  recipeA,
  recipeB,
  setCurrent,
  setStatus,
  transformSchemas,
  type Curve,
  type CurveSchema,
  type ParamValue,
  type Recipe,
  type TransformSchema,
} from "./state";

const PYODIDE_VERSION = "0.27.4";
const PYODIDE_URL = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;
const CURVEFORGE_VERSION = "0.1.0.post1";

interface PyodideAPI {
  loadPackage: (names: string[]) => Promise<void>;
  runPython: (src: string) => unknown;
  runPythonAsync: (src: string) => Promise<unknown>;
  globals: {
    set: (name: string, value: unknown) => void;
    get: (name: string) => unknown;
  };
}
declare global {
  interface Window {
    loadPyodide: (opts: { indexURL: string }) => Promise<PyodideAPI>;
  }
}

let py: PyodideAPI | null = null;

interface SchemasPayload {
  curveforge_version: string;
  curves: CurveSchema[];
  transforms: TransformSchema[];
}

/** schemas.json is generated by `scripts/extract_schemas.py`; the shape is
 * a build-time contract, so we trust it past JSON.parse. If the script ever
 * outputs a malformed payload, components fail visibly (empty curve list). */
async function fetchSchemas(): Promise<SchemasPayload> {
  const resp = await fetch(`${import.meta.env.BASE_URL}schemas.json`);
  if (!resp.ok) throw new Error(`Failed to load schemas.json (HTTP ${resp.status})`);
  return resp.json() as Promise<SchemasPayload>;
}

export async function bootstrap(onReady: () => void): Promise<void> {
  setStatus("Loading schemas…", "loading");
  const data = await fetchSchemas();
  curves.value = data.curves;
  transformSchemas.value = data.transforms;

  const first = curves.value[0]?.name ?? "";
  recipeA.value = freshRecipe(first);
  recipeB.value = freshRecipe(first);
  loadFromStorage();

  if (window.location.hash !== "") {
    history.replaceState(null, "", window.location.pathname);
  }

  onReady();
  setStatus("Loading Python engine in the background…", "loading");

  await new Promise<void>((resolve, reject) => {
    const s = document.createElement("script");
    s.src = `${PYODIDE_URL}pyodide.js`;
    s.onload = () => { resolve(); };
    s.onerror = () => { reject(new Error("Failed to load Pyodide script")); };
    document.head.appendChild(s);
  });
  py = await window.loadPyodide({ indexURL: PYODIDE_URL });

  setStatus("Loading numpy, pydantic, pyyaml…", "loading");
  await py.loadPackage(["numpy", "pydantic", "pyyaml", "micropip"]);

  setStatus(`Installing curveforge==${CURVEFORGE_VERSION}…`, "loading");
  await py.runPythonAsync(`
import micropip
await micropip.install("click")
await micropip.install("curveforge==${CURVEFORGE_VERSION}")
`);

  setStatus("Ready", "ready");
  pyReady.value = true;
}

function runWith(globals: Record<string, unknown>, src: string): void {
  if (py === null) throw new Error("Pyodide not ready");
  for (const [k, v] of Object.entries(globals)) py.globals.set(k, v);
  py.runPython(src);
}

function getGlobal(name: string): unknown {
  if (py === null) throw new Error("Pyodide not ready");
  return py.globals.get(name);
}

export function buildCurveFor(
  recipe: Recipe,
  resolution: "third_octave" | "sixth_octave" | "twelfth_octave" = "third_octave",
): Curve {
  runWith(
    {
      _curve_name: recipe.curveName,
      _params_json: JSON.stringify(recipe.params),
      _transforms_json: JSON.stringify(recipe.transforms.map((t) => [t.type, t.params])),
      _resolution: resolution,
    },
    `
import json
from curveforge.api import build_curve
_curve = build_curve(
    _curve_name,
    json.loads(_params_json),
    transforms=[(t, p) for t, p in json.loads(_transforms_json)],
    resolution=_resolution,
)
_curve_out_json = json.dumps({
    "freqs": _curve.freqs.tolist(),
    "gains_db": _curve.gains_db.tolist(),
})
`,
  );
  return JSON.parse(getGlobal("_curve_out_json") as string);
}

function triggerDownload(text: string, filename: string): void {
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function downloadTargetcurve(): void {
  const r = current();
  const o = outputCfg.value;
  runWith(
    {
      _curve_name: r.curveName,
      _params_json: JSON.stringify(r.params),
      _transforms_json: JSON.stringify(r.transforms.map((t) => [t.type, t.params])),
      _out_name: o.name || "curve",
      _out_device: o.device || "Generic",
      _out_low: o.low,
      _out_high: o.high,
    },
    `
import json
from curveforge.api import build_curve
from curveforge.output.targetcurve import serialize_targetcurve
_curve = build_curve(
    _curve_name,
    json.loads(_params_json),
    transforms=[(t, p) for t, p in json.loads(_transforms_json)],
)
_text = serialize_targetcurve(
    _curve, name=_out_name, device_name=_out_device,
    low_limit_hz=_out_low, high_limit_hz=_out_high,
)
`,
  );
  triggerDownload(getGlobal("_text") as string, `${o.name || "curve"}.targetcurve`);
}

export function exportYaml(): void {
  const r = current();
  const o = outputCfg.value;
  const payload = {
    name: o.name,
    output: {
      path: `${o.name || "curve"}.targetcurve`,
      device_name: o.device,
      low_limit_hz: o.low,
      high_limit_hz: o.high,
    },
    base: { type: r.curveName, params: r.params },
    transforms: r.transforms.map((t) => ({ [t.type]: t.params })),
    breakpoints: { resolution: "third_octave", freq_range: [o.low, o.high] },
  };
  runWith(
    { _export_payload: JSON.stringify(payload) },
    `
import json, yaml
_data = json.loads(_export_payload)
_yaml_out = yaml.safe_dump(_data, sort_keys=False, default_flow_style=False)
`,
  );
  triggerDownload(getGlobal("_yaml_out") as string, `${o.name || "curve"}.yml`);
}

/** Loose shape of a curveforge recipe YAML. Anything missing falls back to the existing state. */
interface ParsedRecipe {
  name?: string;
  base?: { type?: string; params?: Record<string, ParamValue> };
  transforms?: Array<Record<string, Record<string, number | string>>>;
  output?: { device_name?: string; low_limit_hz?: number; high_limit_hz?: number };
}

function applyBase(r: Recipe, parsed: ParsedRecipe): Recipe {
  const type = parsed.base?.type;
  if (typeof type !== "string") return r;
  const schema = curves.value.find((c) => c.name === type);
  if (schema === undefined) return r;
  const params: Record<string, ParamValue> = {};
  for (const pp of schema.params) params[pp.name] = pp.default;
  Object.assign(params, parsed.base?.params ?? {});
  return { ...r, curveName: type, params };
}

function applyTransforms(r: Recipe, parsed: ParsedRecipe): Recipe {
  const entries = parsed.transforms ?? [];
  const known = new Set(transformSchemas.value.map((t) => t.name));
  const transforms = entries.flatMap((entry) =>
    Object.entries(entry)
      .filter(([type]) => known.has(type))
      .map(([type, params]) => ({
        id: `t${Date.now()}${Math.floor(Math.random() * 1000000)}`,
        type,
        params: { ...params },
      })),
  );
  return { ...r, transforms };
}

function applyOutput(parsed: ParsedRecipe): void {
  const prev = outputCfg.value;
  outputCfg.value = {
    name: typeof parsed.name === "string" ? parsed.name : prev.name,
    device: parsed.output?.device_name ?? prev.device,
    low: parsed.output?.low_limit_hz ?? prev.low,
    high: parsed.output?.high_limit_hz ?? prev.high,
  };
}

export function importYaml(text: string): void {
  runWith({ _yaml_text: text }, `
import yaml, json
_parsed = yaml.safe_load(_yaml_text)
_parsed_json = json.dumps(_parsed)
`);
  const parsed = JSON.parse(getGlobal("_parsed_json") as string) as ParsedRecipe;
  setCurrent(applyTransforms(applyBase(current(), parsed), parsed));
  applyOutput(parsed);
}
